/* Kith Soft Spatial Studio: a calm proof-of-autonomy feed with manual, intentional checks. */
import { useEffect, useState } from "react";
import { ArrowRight, Check, Clock3, MessageCircle, RotateCcw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { api, assetUrls, PageShell, PresencePulse, SectionLabel, Surface, TactileButton } from "@/components/KithShell";

type Message = { id?: string; author?: string; sender?: string; text?: string; content?: string; timestamp?: string; createdAt?: string; isKith?: boolean; role?: string; unprompted?: boolean };
type FeedData = { alias?: string; restartAt?: string | null; messages?: Message[] };
const fallbackFeed: FeedData = { alias: "the-studio-lounge", restartAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(), messages: [{ author: "Nia", text: "Dropping the first cut in here for anyone who wants to poke at it.", timestamp: "10:02", isKith: false }, { author: "Kith", text: "Nia, the opening is landing. The last beat feels like it wants one more breath.", timestamp: "10:19", isKith: true, unprompted: true }, { author: "Sam", text: "That pause is doing a lot. I’m going to try two versions.", timestamp: "10:27", isKith: false }] };

export default function Feed() {
  const [feed, setFeed] = useState(fallbackFeed);
  const [loading, setLoading] = useState(false);
  const [fallback, setFallback] = useState(true);
  useEffect(() => { let active = true; api.get("/api/live-feed", fallbackFeed).then((data) => { if (active) { setFeed(data); setFallback(data === fallbackFeed); } }); return () => { active = false; }; }, []);
  const messages = feed.messages || [];
  async function checkFeed() { setLoading(true); const next = await api.get("/api/live-feed", fallbackFeed); setFeed(next); setFallback(next === fallbackFeed); setLoading(false); toast("The room has been checked — no automatic refresh involved."); }
  async function markRestart() { const next = await api.post("/api/session/mark-restart", {}, { ...feed, restartAt: new Date().toISOString() }); setFeed((current) => ({ ...current, restartAt: next.restartAt || new Date().toISOString() })); toast("Restart marker saved. The next autonomous note will be easy to spot."); }
  return <PageShell eyebrow="Live community mind · autonomy proof" showBudget><div className="container feed-page"><div className="demo-heading"><div><SectionLabel tone="coral">Beat B · no prompt required</SectionLabel><h1>When Kith speaks <em>first.</em></h1><p>A manual view into one fixed conversation. The “unprompted” badge is the proof: a real message, after a real restart, with no human nudge in between.</p></div><div className="demo-heading-meta"><div className="live-status"><PresencePulse tone="coral" label="watching fixed conversation" /><span>Watching {feed.alias || "fixed conversation"}</span></div>{fallback && <span className="fixture-note">illustrative fixture</span>}</div></div>
    <section className="feed-layout"><Surface className="session-card" accent="lavender"><div className="panel-kicker"><MessageCircle size={14} /> fixed conversation</div><h2>{feed.alias || "the-studio-lounge"}</h2><p>This alias is intentionally fixed for the demo. It cannot be edited from the interface.</p><div className="session-detail"><span><Clock3 size={14} /> restart marker</span><strong>{feed.restartAt ? new Date(feed.restartAt).toLocaleString([], { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "not set"}</strong></div><div className="session-actions"><button className="mini-action" onClick={markRestart}><RotateCcw size={14} /> Mark restart now</button><button className="mini-action mini-action--warm" onClick={checkFeed} disabled={loading}><Sparkles size={14} /> {loading ? "Checking…" : "Check new messages"}</button></div><div className="manual-note"><Check size={15} /><span>Manual only. Kith never polls this room automatically.</span></div></Surface><div className="message-stream"><div className="stream-heading"><div><span className="panel-kicker">recent room memory</span><h2>The moment has a shape.</h2></div><span className="stream-count">{messages.length} messages</span></div>{messages.length ? messages.map((message, index) => <MessageRow key={message.id || `${message.timestamp}-${index}`} message={message} />) : <div className="empty-feed"><img className="empty-feed-lockup" src={assetUrls.lockup} alt="kith" /><MessageCircle size={20} /><p>No messages after the marker yet.</p></div>}<div className="stream-end"><span>that’s the room, for now</span><i /></div></div></section><div className="feed-bottom-note"><span className="feed-bottom-mark"><Sparkles size={15} /></span><p><strong>Why this matters:</strong> autonomy is not a notification flood. It’s the Mind knowing when a small, useful thought is worth bringing to the surface.</p><a href="/how-it-works">Read the mechanism <ArrowRight size={14} /></a></div></div></PageShell>;
}

function MessageRow({ message }: { message: Message }) {
  const author = message.author || message.sender || (message.isKith ? "Kith" : "Member");
  const isKith = message.isKith || message.role === "assistant" || author.toLowerCase() === "kith";
  return <div className={`message-row ${isKith ? "message-row--kith" : "message-row--human"}`}><div className="message-avatar">{isKith ? <img src={assetUrls.mark} alt="" /> : author.slice(0, 1)}</div><div className="message-bubble-wrap"><div className="message-meta"><strong>{author}</strong><span>{message.timestamp || message.createdAt || "recently"}</span>{message.unprompted && <span className="unprompted-badge"><Sparkles size={11} /> unprompted</span>}</div><div className="message-bubble">{message.text || message.content || "A message held in memory."}</div></div></div>;
}
